### ISSUE TITLE
Jupyter notebook matplotlib qt5

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy-bundle#30]
With the current version of the HyperSpy WinPython bundle (
HyperSpy-Bundle-2018.09.04-3.6.3-64bit.exe), using `%matplotlib qt5` in Jupyter Notebooks gives the error: `RunTimeError: Cannot activate multiple GUI eventloops`.

Using `%matplotlib qt` works fine.

I have not tried this in the Anaconda environment, so the issue might be present there as well.

**Comment by francisco-dlp** [comment]
The issue is not present for me when using anaconda linux.

**Comment by ericpre** [comment]
I don't think that there anything that we can do in the bundle except maybe setting a matplotlib configuration in the python distribution but it doesn't sound like a good idea. Anyway, it may not work in all cases, because users can use other configuration file.

The best we can do is to get users to follow the recommendation of the [user guide](https://hyperspy.readthedocs.io/en/stable/user_guide/getting_started.html#starting-hyperspy-in-the-notebook-or-terminal).
