### ISSUE TITLE
Update from previous release

### ISSUE THREAD

**Issue by ricounet67** [hyperspy/hyperspy-bundle#53]
This more a question than an issue.
If the previous release is installed, what is the best way to update hyperspy: reinstall with the next installation program or update through conda update --all ?

**Comment by ericpre** [comment]
If you have a recent version of conda (>=4.10.0) and you don't have any user configuration file (`.condarc`) from previous install or different distribution,`conda update --all` or `mamba update --all` should work fine, because the conda settings are set to play well with `conda-forge` out of the box.

In case you have a user `.condarc` file in your home folder, this file will take precedence over the one included in the distribution and depending what have been set previously (and saved in this file), it may not work! See https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html for more details.

I would recommend to use `mamba` instead of `conda` because it doesn't take as long to the solve the environment and it works as well as conda.

There is still one known bug in a specific case as described in https://github.com/conda/conda/pull/10479#issuecomment-775519701.

Previously, we would not recommend to use `conda update --all` because there was a number of situations where it would not work well, but now it should be fine. Once we are more confident that this is working well, we should document it and also fix the bug mentioned above!

**Comment by ericpre** [comment]
> There is still one known bug in a specific case as described in [conda/conda#10479 (comment)](https://github.com/conda/conda/pull/10479#issuecomment-775519701).

This is now fixed in latest conda release - see https://github.com/conda/conda/pull/10735.
